### Imports

In [1]:
import numpy as np

### Joining (Concatenation)

In [11]:
# Create some dummy data
w_hh = np.full((3,2), 1)
w_hx = np.full((3,3), 9)

'''
array([[1, 1],
       [1, 1],
       [1, 1]])

array([[ 9,  9,  9],
       [ 9,  9,  9],
       [ 9,  9,  9]])
'''

# Try using random initialization
w_hh = np.random.standard_normal((3,2))
w_hx = np.random.standard_normal((3,3))

print("-- Data --\n")
print("w_hh : ")
print(w_hh)
print("w_hx shape : ", w_hh.shape, "\n")
print("w_hx : ")
print(w_hx)
print("w_hx shape : ", w_hx.shape, "\n")

# Joining the arrays
# Option 1: concatenate
w_h1 = np.concatenate((w_hh, w_hx), axis = 1)
print("Option 1 : concatenate\n")
print("w_h")
print(w_h1)
print("w_h shape : ", w_h1.shape, "\n")

# Option 2: hstack
w_h2 = np.hstack((w_hh, w_hx))
print("Option 2 : hstack\n")
print("w_h : ")
print(w_h2)
print("w_h shape : ", w_h2.shape)

-- Data --

w_hh : 
[[ 0.93208287 -1.63138539]
 [-0.80867001 -1.0607575 ]
 [-0.64248324  0.43261805]]
w_hx shape :  (3, 2) 

w_hx : 
[[-1.83803508  1.48732452  0.03243909]
 [ 0.67651248 -1.66896476 -1.39354743]
 [ 1.46974872 -2.72236959  1.00424288]]
w_hx shape :  (3, 3) 

Option 1 : concatenate

w_h
[[ 0.93208287 -1.63138539 -1.83803508  1.48732452  0.03243909]
 [-0.80867001 -1.0607575   0.67651248 -1.66896476 -1.39354743]
 [-0.64248324  0.43261805  1.46974872 -2.72236959  1.00424288]]
w_h shape :  (3, 5) 

Option 2 : hstack

w_h : 
[[ 0.93208287 -1.63138539 -1.83803508  1.48732452  0.03243909]
 [-0.80867001 -1.0607575   0.67651248 -1.66896476 -1.39354743]
 [-0.64248324  0.43261805  1.46974872 -2.72236959  1.00424288]]
w_h shape :  (3, 5)


### Hidden State & Input

In [13]:
# Create some more dummy data
h_t_prev = np.full((2,1), 1)
x_t = np.full((3,1), 9)

h_t_prev = np.random.standard_normal((2,1))
x_t = np.random.standard_normal((3,1))

print("-- Data --\n")
print("h_t_prev :")
print(h_t_prev)
print("h_t_prev shape :", h_t_prev.shape, "\n")
print("x_t :")
print(x_t)
print("x_t shape :", x_t.shape, "\n")

# Joining the arrays
print("-- Joining --\n")

# Option 1: concatenate - vertical
ax_1 = np.concatenate(
    (h_t_prev, x_t), axis=0
)  # note the difference in axis parameter vs earlier
print("option 1 : concatenate\n")
print("ax_1 :")
print(ax_1)
print("ax_1 shape :", ax_1.shape, "\n")

# Option 2: vstack
ax_2 = np.vstack((h_t_prev, x_t))
print("option 2 : vstack\n")
print("ax_2 :")
print(ax_2)
print("ax_2 shape :", ax_2.shape)

-- Data --

h_t_prev :
[[0.54898419]
 [1.05227586]]
h_t_prev shape : (2, 1) 

x_t :
[[ 1.03895513]
 [-0.72566487]
 [-1.94072216]]
x_t shape : (3, 1) 

-- Joining --

option 1 : concatenate

ax_1 :
[[ 0.54898419]
 [ 1.05227586]
 [ 1.03895513]
 [-0.72566487]
 [-1.94072216]]
ax_1 shape : (5, 1) 

option 2 : vstack

ax_2 :
[[ 0.54898419]
 [ 1.05227586]
 [ 1.03895513]
 [-0.72566487]
 [-1.94072216]]
ax_2 shape : (5, 1)


### Verify Formulas

In [17]:
# Data
w_hh = np.full((3, 2), 1)
w_hx = np.full((3, 3), 9)
h_t_prev = np.full((2, 1), 1)
x_t = np.full((3, 1), 9)

# w_hh = np.random.standard_normal((3,2))
# w_hx = np.random.standard_normal((3,3))
# h_t_prev = np.random.standard_normal((2,1))
# x_t = np.random.standard_normal((3,1))

# Results
stack_1 = np.hstack((w_hh, w_hx))
stack_2 = np.vstack((h_t_prev, x_t))

print("\nFormula 1")
print("Term1 : \n",stack_1)
print("Term2 : \n",stack_2)
formula_1 = np.matmul(np.hstack((w_hh, w_hx)), np.vstack((h_t_prev, x_t)))
print("\n Formula 1 Output : ")
print(formula_1)

# Formula 2
formula_2 = np.matmul(w_hh, h_t_prev) + np.matmul(w_hx, x_t)
print("Formula 2 Output : ")
print(formula_2)

print("\n-- Verify --")
print("Results are the same :", np.allclose(formula_1, formula_2))

# # Activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Bias and check
b = np.random.standard_normal((formula_1.shape[0],1))
print("Formula 1 Output:\n",sigmoid(formula_1+b))
print("Formula 2 Output:\n",sigmoid(formula_2+b))

all_close = np.allclose(sigmoid(formula_1+b), sigmoid(formula_2+b))
print("\nResults after activation are the same :",all_close)


Formula 1
Term1 : 
 [[1 1 9 9 9]
 [1 1 9 9 9]
 [1 1 9 9 9]]
Term2 : 
 [[1]
 [1]
 [9]
 [9]
 [9]]

 Formula 1 Output : 
[[245]
 [245]
 [245]]
Formula 2 Output : 
[[245]
 [245]
 [245]]

-- Verify --
Results are the same : True
Formula 1 Output:
 [[1.]
 [1.]
 [1.]]
Formula 2 Output:
 [[1.]
 [1.]
 [1.]]

Results after activation are the same : True
